apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dice
  name: dice
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dice
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - image: dice:1.0
        imagePullPolicy: IfNotPresent
        name: dice
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        env:
          - name: USERS_URL
            value: http://users:8081/
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
