apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simple
  namespace: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:

    exporters:
      debug:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write
      
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [debug, prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [debug]