apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simple
  namespace: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      resource:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: service.name, k8s.pod.name, k8s.container.name, k8s.namespace.name

    exporters:
      debug:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write
      loki:
        endpoint: http://loki-gateway.monitoring/loki/api/v1/push
      otlp/tempo:
        endpoint: tempo.monitoring:4317
        tls:
          insecure: true
      
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlp/tempo]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [debug, prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [resource]
          exporters: [debug, loki]